In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import os
from utils.activations import softmax, sigmoid

np.random.seed(1)

#define constants
num_class = 4 # no of classes
hidden_layer_units = 25  #number of units in the hidden layer
epochs = 150
alpha = 0.001 #learning rate 


## DataSource
X_train, Y_train is parsed from csv files 

In [2]:
x = pd.read_csv(os.path.join('data','train_data.csv'), header=None).add_prefix('Feature_')
y = pd.read_csv(os.path.join('data', 'train_labels.csv'), header=None, names=["Label_0", "Label_1", "Label_2", "Label_3"])
X_train = x.values
Y_train = y.values
m, n = X_train.shape

## Layer and Forward Propagation
We then implement Layer and For-prop as follow

In [3]:
def Layer(A_in, W, B, g):
    """
    :param A_in: shape(m,n) - input data
    :param W: shape(feature,units) - weight matrix, n0 feature  x units, 
    :param b: shape(units,1) - bias vector, n0 units x 1
    :param g: activation function(e.g sigmoid, relu, softmax, ...)
    :return:
    A_out: shape(m, units): output data - m x units
    """
    Z = np.dot(A_in, W) + B
    A_out = g(Z)
    return Z,A_out

In [4]:
def compute_forward_prop(x, W1, b1, W2, b2):
    z1, a1 = Layer(x, W1, b1, sigmoid)  #hidden layer with sigmoid activation
    z2, a2 = Layer(a1, W2, b2, softmax) #output layer with softmax activation
    return z1, a1, z2, a2

## Initialize model parameters
The model parameters are intialized randomly as follow:

In [5]:

def initialize_model_params():
    W1 = np.random.randn(n, hidden_layer_units)
    b1 = np.random.randn(hidden_layer_units)
    W2 = np.random.randn(hidden_layer_units, num_class)
    b2 = np.random.randn(num_class)
    return b1, W1, b2, W2

## Back propagation

In [6]:
def sigmoid_derivative(x): 
    return sigmoid(x) * (1 - sigmoid(x))

def compute_backward_prop(Z1, A1, A2, W2,X, Y): 
    dz2 = A2 - Y
    dW2 = np.dot(A1.T,dz2)
    db2 = dz2
    dz1 = np.dot(dz2,W2.T)
    db1 = dz2 * sigmoid_derivative(dz1)
    dW1 = np.dot(X.T,dz1 * sigmoid_derivative(dz1))
    return db1, dW1, db2, dW2

## Gradient descent 

In [7]:
def update_model_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha_):
    if dW1.shape == (n, hidden_layer_units):
        W1 = W1 - alpha_ * dW1
    if dW2.shape == (hidden_layer_units, num_class):
        W2 = W2 - alpha_ * dW2
    if db1.shape == (m, hidden_layer_units):
        b1 = b1 - alpha_ * db1.sum(axis=0)
    if db2.shape == (m, num_class):
        b2 = b2 - alpha_ * db2.sum(axis=0)
    return b1, W1, b2, W2

## Cost function

In [ ]:
def cost(y_hat, y):
    return np.mean(np.square(y_hat - y))

## Prediction and accuracy
In order to analyze the results, the implementation of prediction and accuracy are described below:  

In [8]:
def predict_from_output_layer(A2):
    return np.argmax(A2, 0)

def predict(X, B1, W1, B2, W2):
    Z1 = np.dot(X, W1) + B1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + B2
    A2 = softmax(Z2)
    prediction = np.argmax(A2, 0)
    return prediction

def accuracy(Y_hat, Y):
    # print(Y_hat, Y)
    return np.sum(Y_hat == Y) / Y.size

## Wrap everything up  

In [12]:
def training_data(X, Y, epochs, alpha):
    B1, W1, B2, W2 = initialize_model_params()
    for i in range(epochs):
        z1, a1, z2, a2 = Sequence(X, W1, B1, W2, B2)
        db1, dW1, db2, dW2 = compute_back_prop(z1, z2, a1, a2, W2, X, Y) 
        b1, W1, b2, W2 = compute_gradient_descent(W1, B1, W2, B2, dW1, db1, dW2, db2, alpha)
        # if i % 10 == 0:
        print("Iteration: ", i)
        print(a2)
        # print(f"Accuracy: {accuracy(convert_to_one_hot(a2), Y)}")
    return b1, W1, b2, W2

Run the training process with $epochs=100$:

In [13]:
b1, W1, b2, W2 = training_data(X_train, Y_train, epochs, alpha)

Iteration:  0
[[0.08696378 0.38444361 0.49061505 0.03797756]
 [0.08696378 0.38444361 0.49061505 0.03797756]
 [0.08696378 0.38444361 0.49061505 0.03797756]
 ...
 [0.08696378 0.38444361 0.49061505 0.03797756]
 [0.08696379 0.38444361 0.49061504 0.03797756]
 [0.08696378 0.38444361 0.49061505 0.03797756]]
Iteration:  1
[[0.0936078  0.38734685 0.47757559 0.04146976]
 [0.0936078  0.38734685 0.47757559 0.04146976]
 [0.0936078  0.38734685 0.47757559 0.04146976]
 ...
 [0.0936078  0.38734685 0.47757559 0.04146976]
 [0.09360781 0.38734684 0.47757558 0.04146977]
 [0.0936078  0.38734685 0.47757559 0.04146976]]
Iteration:  2
[[0.10036885 0.38912296 0.46536507 0.04514312]
 [0.10036885 0.38912296 0.46536507 0.04514312]
 [0.10036885 0.38912296 0.46536507 0.04514312]
 ...
 [0.10036885 0.38912296 0.46536507 0.04514312]
 [0.10036886 0.38912295 0.46536506 0.04514313]
 [0.10036885 0.38912296 0.46536507 0.04514312]]
Iteration:  3
[[0.1072092  0.38990705 0.45389085 0.04899289]
 [0.1072092  0.38990705 0.4538908

Now, we have the proper arguments for out the model. Let's try some unseen tests:

In [11]:
# X_test = np.random.rand(1, n)
# prediction = predict(X_test, b1, W1, b2, W2)
# print(f"prediction = {prediction}")
# print(f"W1 = {W1}")